name: Ferret CI (monorepo)

on:
  pull_request:
    branches: [main]

jobs:
  ferret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SpecFerret CI
        uses: BenGardiner123/action@v1
        with:
          baseline-mode: committed
          working-directory: .
          artifact-name: ferret-lint-ci-monorepo
